### ISSUE TITLE
Patch DSL: support patching multiple modules with one statement

### ISSUE THREAD

**Issue by jjohannes** [gradlex-org/jvm-dependency-conflict-resolution#127]
Should be able to write:

```
jvmDependencyConflicts {
    patch {
        module("org.openjfx:javafx-base", "org.openjfx:javafx-graphics") {
            addTargetPlatformVariant("", "none", "none")
            addTargetPlatformVariant("linux", OperatingSystemFamily.LINUX, MachineArchitecture.X86_64)
            addTargetPlatformVariant("mac", OperatingSystemFamily.MACOS, MachineArchitecture.X86_64)
            addTargetPlatformVariant("mac-aarch64", OperatingSystemFamily.MACOS, MachineArchitecture.ARM64)
            addTargetPlatformVariant("win", OperatingSystemFamily.WINDOWS, MachineArchitecture.X86_64)
        }
    }
}
```

**Comment by britter** [comment]
If patching for OS specific artifacts is a common use case, maybe we can come up with an even more compat way of declaring just that in addition.

**Comment by jjohannes** [comment]
Just realized that this signature is (of course) not possible in Java:

```
public void module(String... modules, Action<PatchModule> action)
```

**Comment by britter** [comment]
If you want to have varargs the only way I see to get this working would be a method chain like the following:

```
jvmDependencyConflicts {
  patch {
    modules("org.openjfx:javafx-base", "org.openjfx:javafx-graphics").each {
       ...
    }
  }
}
```

The `modules` method would have the following signature:

```
public EachModuleConfigurer modules(String... modules);

interface EachModuleConfigurer { 
  public void each(Action<PatchModule> action)
}
```

But this would just wrap around a forEach call and would spare you from writing `listOf`. Not sure if this is really better. The problem with these kind of chaining APIs is always when you forget to make the terminal call nothing happens. And that is sometimes hard to find.

**Comment by jjohannes** [comment]
Lets not do this now. I would prefer not to overload the DSL unless there is a really clean DSL concept (and not a technical API).
