### ISSUE TITLE
Javax and Jakarta Activation capabilites for com.sun.activation

### ISSUE THREAD

**Issue by lennartfricke** [gradlex-org/jvm-dependency-conflict-resolution#152]
It seems to me that the Jakarta activation capability definition adds the jakarta capability to the com.sun.activation artifacts that still contain the javax packages (version 1.2.2, 1.2.1).

I would have expected the verion 1.2.1,2 to have the javax capability added and the newer versions with the jakarta capability.

**Comment by jjohannes** [comment]
Thank you for reporting @lennartfricke.

The `JAKARTA_ACTIVATION_API` capability is handled correctly, but we missed doing the same for `JAKARTA_ACTIVATION_IMPL`.

**Comment by jjohannes** [comment]
Release `2.1.2` with the fix
