### ISSUE TITLE
IntelliJ project sync fails though CLI build succeeds

### ISSUE THREAD

**Issue by sschuberth** [gradlex-org/jvm-dependency-conflict-resolution#159]
After applying and configuring the `org.gradlex.jvm-dependency-conflict-resolution` plugin so that the Gradle CLI build succeeds, interestingly the IntelliJ IDEA project sync fails with:

```
Problems reading data from Binary store in /home/sebastian/.gradle/.tmp/gradle13035720159068604309.bin offset 79537 exists? true
Problems loading the resolution results (0.0 secs). Read 659 values, last was: 5
Corrupt serialized resolution result. Cannot find selected variant (55942) for runtime -> org.apache.logging.log4j:log4j-slf4j-impl:2.17.2
```

This seems to be somehow caused by

```
jvmDependencyConflicts {
    logging {
        enforceLogback()
    }
}
```

Checkout https://github.com/oss-review-toolkit/ort/tree/jvm-dependency-conflict-resolution to reproduce.

Versions:
Gradle 8.10
Kotlin 2.0.20
`org.gradlex.jvm-dependency-conflict-resolution` plugin 2.1.2
IntelliJ IDEA 2024.2.0.2

**Comment by jjohannes** [comment]
Thanks for reporting. This looks very much like the issue(s) in Gradle linked here: #93

The bug sometimes only materializes when the dependency resolution result is serialized and then loaded again. A plain build sometimes does not do the loading part, but the IDE import does. You most likely also get the issue when you run with `--scan`.

The Gradle team is working on fixing these issues. If you have a reproducer, it would be great if you can share it here where reproducers are collected: https://github.com/gradle/gradle/issues/14220

I am closing this as duplicated of #93.
