### ISSUE TITLE
Resolution does not seem to work with custom source sets

### ISSUE THREAD

**Issue by sschuberth** [gradlex-org/jvm-dependency-conflict-resolution#169]
I have

```
jvmDependencyConflicts {
    conflictResolution {
        select(CapabilityDefinition.JAVAX_ACTIVATION_API, "jakarta.activation:jakarta.activation-api")
    }
}
```

but still I get

```
> Could not resolve all files for configuration ':cli:funTestCompileClasspath'.
   > Could not resolve jakarta.activation:jakarta.activation-api:2.0.1.
     Required by:
         project :cli > com.icegreen:greenmail:2.0.1
      > Module 'jakarta.activation:jakarta.activation-api' has been rejected:
           Cannot select module with conflict on capability 'org.gradlex:jakarta-activation-api:2.0.1' also provided by [com.sun.activation:jakarta.activation:2.0.1(compile)]
   > Could not resolve com.sun.activation:jakarta.activation:2.0.1.
     Required by:
         project :cli > com.icegreen:greenmail:2.0.1 > com.sun.mail:jakarta.mail:2.0.1
      > Module 'com.sun.activation:jakarta.activation' has been rejected:
           Cannot select module with conflict on capability 'org.gradlex:jakarta-activation-api:2.0.1' also provided by [jakarta.activation:jakarta.activation-api:2.0.1(compile)]
```

when running `./gradlew funTestClasses` on my custom `funTest` source set defined as

```
testing {
    suites {
        register<JvmTestSuite>("funTest") {
            sources {
                kotlin {
                    testType = TestSuiteType.FUNCTIONAL_TEST
                }
            }
        }
    }
}
```

**Comment by jjohannes** [comment]
@sschuberth I don't thin this is specific to a custom source set. The default resolution strategy the plugin adds is `selectHighestVersion()`. If that is not sufficient to make a descission, you will have to give a resolution strategy yourself.

The error states:
```
Cannot select module with conflict on capability 'org.gradlex:jakarta-activation-api:2.0.1' also provided by [com.sun.activation:jakarta.activation:2.0.1(compile)]
```

Notice how both alternatives have the same version: `2.0.1`. There is no highest and no solution can be found.

You can resolve this be adding, for example:

```
jvmDependencyConflicts {
    conflictResolution {
        select(CapabilityDefinition.JAKARTA_ACTIVATION_API, "jakarta.activation:jakarta.activation-api")
    }
}
```

See: [docs on Customize resolution of capability conflicts](https://gradlex.org/jvm-dependency-conflict-resolution/#conflictResolution-dsl-block)

**Comment by sschuberth** [comment]
I'm giving it a new try at https://github.com/oss-review-toolkit/ort/pull/9181 with all of

    select(CapabilityDefinition.JAKARTA_ACTIVATION_API, "jakarta.activation:jakarta.activation-api")
    select(CapabilityDefinition.JAVAX_ACTIVATION_API, "jakarta.activation:jakarta.activation-api")
    select(CapabilityDefinition.JAVAX_INJECT_API, "jakarta.inject:jakarta.inject-api")

Still looks weird that I basically have to resolve `JAKARTA_ACTIVATION_API` to itself...

**Comment by jjohannes** [comment]
> Still looks weird that I basically have to resolve JAKARTA_ACTIVATION_API to itself...

The first argument is the Capability. The second is the Module to select.

Maybe you want to use `com.sun.activation:jakarta.activation` as second argument.

Depending on whether you want only the API only (`jakarta.activation:jakarta.activation-api`) or API+implementation (`com.sun.activation:jakarta.activation`). As this depends on what your setup needs, there is no "one fits all" solution the plugin can provide as default.

The `selectHighestVersion()` default is already a "best guess" to have some default so that users do not need to handle all conflicts themself. (We also considered having no defaults at all.)

**Comment by sschuberth** [comment]
I'm now running into a bunch of [more](https://github.com/oss-review-toolkit/ort/actions/runs/11698939074/job/32580068483?pr=9181#step:7:49) [problems](https://github.com/oss-review-toolkit/ort/actions/runs/11698939074/job/32580068483?pr=9181#step:7:89). At this point, investigating the issues exceeds my set time box for the experiment to take this plugin into use. Thanks for your help, but I'm giving up for now.

**Comment by sschuberth** [comment]
> @sschuberth please try Gradle version `8.11-rc-2`. It supposedly fixed the bug(s) that causing the `Problems reading data from Binary` error when using this plugin.

Thanks for the note. I'll take Gradle 8.11 final into use once it's released, and then eventually try again.
