### ISSUE TITLE
Extend rule for `org.bouncycastle`

### ISSUE THREAD

**Issue by boris-petrov** [gradlex-org/jvm-dependency-conflict-resolution#17]
There are `org.bouncycastle:bcprov-jdk15on` and `org.bouncycastle:bcprov-jdk18on` which are conflicting.

Same for `bcmail`, `bcutil`, `bcpkix` and maybe others.

**Comment by jjohannes** [comment]
This would be a candidate to solve like we did for Guava in the past. If the Java version used defines which variant to pick, we could merge all variants together into a single component (from the Gradle viewpoint) and then use the [org.gradle.jvm.version](https://docs.gradle.org/current/javadoc/org/gradle/api/attributes/java/TargetJvmVersion.html#TARGET_JVM_VERSION_ATTRIBUTE) attribute (and not capabilities) for Gradle to decide based on the Java version.

See this example: https://docs.gradle.org/current/userguide/component_metadata_rules.html#making_variants_encoded_in_versions_explicit

**Comment by jjohannes** [comment]
Okay that's crazy:

![bcprov](https://user-images.githubusercontent.com/1963746/214928455-47ab863a-f404-4093-94f9-9589d3b384bb.jpg)


Let's just do the capabilities similar to the other libraries at first.

**Comment by boris-petrov** [comment]
@jjohannes there is also `bcjmail-jdk18on` (note the extra `j`) - that's a Jakarta version of the `bcmail` artifact... so I guess either in this rule or in the Jakarta vs javax rules this could be added... not sure how exactly. This is complete madness. :smile:

**Comment by boris-petrov** [comment]
@jjohannes sorry to ping you again but you might have missed this. :)

**Comment by jjohannes** [comment]
Thanks for the ping.
