### ISSUE TITLE
Revisit code structure and final 2.0 preparations

### ISSUE THREAD

**Issue by britter** [gradlex-org/jvm-dependency-conflict-resolution#70]
Move things into appropriate packages after merge with logging plugin

**Comment by jjohannes** [comment]
Also check the formatting of `CapabilityDefinitions.java` – see remarks on that here: #96

**Comment by jjohannes** [comment]
Incomplete list of things to do:

Code
- [ ]  Name of extension `jvmDependencyConflicts` ? Name of the "blocks" inside ok?
- [ ] Rename: `CapabilityDefinitions` -> `CapabilityDefinition` / `AlignmentDefinitions` -> `AlignmentDefinition` ?
- [ ] Change package names
- [ ] Double check plugin names and descriptions
- [ ] Can `ConflictResolution.getDeactivatedResolutionStrategies()` be not public
- [ ] Decide on #94 (how to implement alignment)
- [ ] More documentation in #92

Meta:
- [ ] Rename repository
- [ ] "Transition" versions of old plugins
